teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: -0.5       # change this to -0.5 where - is to reverse the direction and 0.5 to make it slower 
    scale_linear_turbo:
      x: -1.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: -0.4 # chnage it to -0.4 to make reverse the diraction of rotation 

    enable_button: 4  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
